FROM maven:3.8.3-openjdk-17 AS builder

COPY ./ProjectChat/src/ /root/src
COPY ./ProjectChat/pom.xml /root/
COPY ./ProjectChat/checkstyle.xml /root/
WORKDIR /root
RUN mvn package -DskipTests
RUN java -Djarmode=layertools -jar /root/target/ProjectSD-0.0.1-SNAPSHOT.jar list
RUN java -Djarmode=layertools -jar /root/target/ProjectSD-0.0.1-SNAPSHOT.jar extract
RUN ls -l /root

FROM openjdk:17-jdk-slim-buster

ENV TZ=UTC
ENV PORT=8080   

COPY --from=builder /root/dependencies/ ./
COPY --from=builder /root/snapshot-dependencies/ ./

RUN sleep 10
COPY --from=builder /root/spring-boot-loader/ ./
COPY --from=builder /root/application/ ./
ENTRYPOINT ["java", "org.springframework.boot.loader.launch.JarLauncher","-XX:+UseContainerSupport -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1 -Xms512m -Xmx512m -XX:+UseG1GC -XX:+UseSerialGC -Xss512k -XX:MaxRAM=72m"]
