FROM node:18-alpine

COPY ./ProjectFrontend /usr/src/app

WORKDIR /usr/src/app

RUN npm install -g @angular/cli

RUN npm install --legacy-peer-deps

EXPOSE 4200

CMD ["ng", "serve", "--host", "0.0.0.0"]
